### ISSUE TITLE
removing the background

### ISSUE THREAD

**Issue by EveTC** [hiweller/colordistance#1]
Hello,

Firstly thanks for the package, it looks like it will be really useful!
I have had a play on some test images, example below:
![PA_1_WW_02_D_calibrated](https://user-images.githubusercontent.com/38794463/61136560-cad05000-a4bb-11e9-9c79-cc6769ddb50a.jpg)

As you can see some my background is not white (after claibration) and some of the colours are close to the background (other wings are ligter and are even more similar to the background), which means that it hard to remove these pixels using the lower and upper in the plotpixels() function. Well on my test run it seems to change the plot but does not remove the background colour as far as I can see (it isnt obvious that it is doing anything).

To get around this I was looking at your flounder example and its seems that you outline the fish and delete the background? Was this done manually? I will have over 2000 images to analyse like the above and am hoping there is a way to automate this step?

I look forward to hearing from you.
Thanks,
Eve

**Comment by alexiaakbay** [comment]
Hi Eve! Did you ever hear back regarding the background coloration? I have similar questions regarding my research.

**Comment by hiweller** [comment]
Hi Eve and Alexia!

Currently, colordistance doesn't make any attempt to find the outline of an object in an image; the only option for masking out the background is specifying a color range to eliminate. This usually works well enough, but you're right that in the case where some patches of color on your object fall within the range of the background color, you'll start to run into problems.

Automatic object/outline detection would be a really nice feature, but it's also a very different kind of image analysis from what colordistance is currently equipped to do; unfortunately I just don't have the kind of time to dedicate to this project that it would take to add that in. The other option, which is specifying more complicated color ranges for pixel masking, is something I should definitely implement. It's in my plans!

Luckily there are many programs that will do this for you semi-automatically -- Photoshop or GIMP should both be able to mask the background using edge detection in a couple of clicks (and I think you can batch process images in both of those programs, so you may not have to do it to all 2000 images manually). So what I would do is change that background color to something easier to mask out, like bright green or magenta, then use that as your background masking value.

Hope that helps, although I'm sorry I couldn't provide an immediate solution!

**Comment by EveTC** [comment]
Hi Alexia,

As Hannah mentioned there isn't a way to do this directly using colordistance. 

However, I solved my issue with the background by creating a macro in ImageJ (FiJi distribution). The macro uses a thresholding method to select the object (wing in my case) and change the colour of the background (to whatever you decide). It can do this automatically across thousands of images. It works well if all your images are very similar, otherwise you may need different threshold methods on images that are different colours.

I changed my background to bright blue so when I then imported into colordistance it was easier to ensure that I was only removing the blue pixels and none of the wings. I also suggest using **.png** images as it holds much more info than **.jpeg**. Also for some reason the new blue background is a single value in the **.png** image as opposed to a range in a **.jpeg** image, so much easier to remove using colordistance.

If you are interested in the macro you can find where I also got help on it here: [https://forum.image.sc/t/removing-changing-background-automatically-for-thousands-of-images/27991](url)

If you do go down this route I suggest testing which threshold method is the best for your images by following these steps:

1. Open an image in imageJ
2. Convert image to 8-bit (Image > Type > 8-bit)
3. Test all threshold method (Image > Adjust > Auto Threshold > (make sure Method is selected to Try all) OK).
4. Select which threshold method has highlighted your object in black the best. Don't worry about holes in the middle of the object as the macro fills these in. Just make sure the outline of your shape is correct. The order of images from left - right in rows relates to the drop down of threshold method in the pop-out you selected "Try all" in, so you can work out which method is the best.

I hope this helps, good luck!

**Comment by EveTC** [comment]
Sorry the link for the macro doesn't seem to work - or takes me somewhere else:
Try this instead: [https://forum.image.sc/t/removing-changing-background-automatically-for-thousands-of-images/27991?u=evetc](url)

**Comment by alexiaakbay** [comment]
Hi both, 

Thanks so much for the helpful suggestions. Unfortunately the images that I would like to analyze are a bit messy, as the goal is to quantify pest algae on seaweeds (green vs. red). An image is attached below as an example. 

I’ll attempt to use ImageJ as suggested by Eve. If you have any other ideas, input would be greatly appreciated. 

Thanks, 
Alexia
